const firstNames = [
	'Basil',
	'Herbert',
	'Winston',
	'Fredrick',
	'Grumpf',
	'Wilhelm',
	'Theodore',
	'Greasus'
]
const lastNames = [
	'Berrybrook',
	'Deathrump',
	'Wellington',
	'Bloodlord',
	'Firerump',
	'Flamebeard',
	'the Flatulant IV',
	'Thornheart',
	'Ragefist',
	'Goldtooth',
	'Guillemaere'
]
const simCityNames = [
	// 'Franz Ausbeuth',
	// 'Holger Ausbunt',
	// 'Wastl Ballwix',
	// 'Michel Bänger',
	'Xaver Birnenschmaus',
	// 'Olaf Bitterbiß',
	// 'Luis Blunzensee',
	'Louis Blunzensee',
	// 'Engelhart Bontz',
	// 'Gerd Böswig',
	'Frieder Brausewitz',
	// 'Peer Brunsen',
	// 'Hans Bullmann',
	// 'Gustav Bürzel',
	// 'Freddi Dollboehr',
	// 'Kaspar Dotterblum',
	'Klaus Drösenklump',
	// 'Pit Dummke',
	// 'Oskar Dünkelhofer',
	// 'Rudi Durchblick',
	'Ernst Eberschneck',
	'Edgar Ellenpohl',
	// 'Paul Ersazki',
	// 'Erwin Fasel',
	// 'Berthold Fatzke',
	// 'Freddi Fiesewetter',
	// 'Reinhard Fitzelbräu',
	// 'Axel Flachmann',
	'Engelbert Flusenberg',
	// 'Sebastian Gallgentritt',
	// 'Egon Gerngroß',
	// 'Igor Grobloch',
	// 'Waldemar Grünspecht',
	// 'Helmut Haslam',
	// 'Willi Haubald',
	'Valentin Haxenpfeffer',
	// 'Wenzeslaus Hitzig',
	// 'Dagobert Holzweg',
	// 'Rudi Karmichel',
	// 'Jockel Katzmauski',
	// 'Till Klecks',
	// 'Wladimir Klugscheit',
	'Karl Knall',
	// 'Wolf Knüppeldieck',
	// 'Helmut Krauth',
	// 'Oskar Lallbeck',
	// 'Ede Langbeen',
	// 'Kalle Langöhr',
	// 'Fritz Lausmann',
	// 'Eddie Metzger',
	'Wolf Nasenstieb',
	// 'Detlef Onemichel',
	// 'Wendelin Pausback',
	// 'Adalgeiß Pikemann',
	'Samuel Plopps',
	'Markus Rinderbrüh',
	// 'Jens Rotlöffel',
	// 'Ödon Ruckmair',
	// 'Albert Schleibich',
	'Martin Schlürfnich',
	// 'Peter Schnutzelwieser',
	// 'Dagobert Schuhlöffel',
	'Tobias Seitenstich',
	// 'Eduard Spürsinn',
	// 'Pluto Stachelski',
	'Gottlieb Stegreif',
	'Botho Sternschnupf',
	// 'Robbie Sterz',
	// 'Piet Stormke',
	// 'Franz Strammbein',
	// 'Heiner Stünkel',
	// 'Erich Treppwitz',
	// 'Philidor Trugschlüß',
	'Ürdü Tüdelüt',
	// 'Dirk Tümper',
	// 'Theo Unbilt',
	// 'Eddie Untenraus',
	'Golo Unterzwerch',
	// 'Arnulf von Achsenbruch',
	'Arnulf von Wannensteg',
	'Hanno von Büsenstreich',
	// 'Blasius Waldschrag',
	// 'Hugo Wamp',
	// 'Fritz Wangengrün',
	// 'Armin Wannensteg',
	// 'Iwan Wasndeppski',
	// 'Emil Watts',
	// 'Holger Weißnitz',
	'Leo Wellblech',
	// 'Konrad Wexelbald',
	// 'Jörg Wiedeborst',
	// 'Gustav Witzbald',
	'Wilhelm Wohlgemuth',
	// 'Rudolf Wolf',
	// 'Florian Wolkenbruch',
	'Trollo Zahnlos',
	// 'Andreas Zahnstein',
	// 'Karol Ersatzki'
]
